class location_code_dict():
    def area(self):
        self.area = { # type: ignore
            "DP" : "DIP",
            "PM" : "PM",
            "RW" : "Rewinder",
            "SP" : "StockPrep",
            "UT" : "Utility"
        }
        return self.area
    def sub_area(self):
        self.sub_area = {# type: ignore
            "APPR" : "Approach",
            "BSYS" : "BoilerSystem",
            "BROK" : "Broke",
            "CFAN" : "CoolingFan",
            "CCUT" : "CoreCutting",
            "DRYE" : "Dryer",
            "DCOL" : "DustCollecting",
            "EXTR" : "Extractor",
            "FELT" : "Felt",
            "GDOC" : "GrindingDoc",
            "HCRA" : "HoistCrane",
            "HSTA" : "HydraulicStation",
            "LBKP" : "LBKP",
            "MIXG" : "Mixing",
            "NBKP" : "NBKP",
            "OSTA" : "OilStation",
            "PREE" : "PopeReel",
            "PLPR" : "Pulper",
            "REWI" : "Rewind",
            "SSYS" : "SteamSystem",
            "UNWI" : "Unwind",
            "WSYS" : "WaterSystem",
            "WIRE" : "Wire",
            "WRAP" : "Wrapping",
            "ASYS" : "AirSystem",
            "ISYS" : "IPALSystem"
        } 
        return self.sub_area
    def bagian(self):
        self.bagian = { # type: ignore
            "AGIT" : "Agitator",
            "BROL" : "BananaRoll",
            "BLIN" : "Blindreel",
            "BOIL" : "Boiler",
            "BRAK" : "Brake",
            "FWAT" : "FreshWater",
            "CGRA" : "ChainGrate",
            "CHES" : "Chest",
            "CWAT" : "ClearWater",
            "CPUM" : "CondensatePump",
            "CTAN" : "CondensateTank",
            "CNVY" : "Conveyor",
            "CYCL" : "Cyclone",
            "XHDC" : "HDC",
            "DEAI" : "Deairator",
            "DEFL" : "Deflaker",
            "DESU" : "Desuperheater",
            "RUME" : "DrumReel",
            "RUMO" : "DrumRoll",
            "DIRE" : "DrumWireRope",
            "XFAN" : "Fan",
            "FPMP" : "FanPump",
            "FWPM" : "FeedWaterPump",
            "FROL" : "FeltRoll",
            "FILT" : "Filter",
            "VIBS" : "Fine/VibrationScreen",
            "FREG" : "FlowRegulator",
            "FORM" : "FormingArea",
            "ATAN" : "AirTank",
            "CYCL" : "Cyclone",
            "HEAD" : "Headbox",
            "HEEX" : "HeatExchanger",
            "HOOD" : "Hood",
            "HOOK" : "Hook",
            "KOMP" : "Kompresor",
            "KROF" : "Krofta",
            "LINE" : "Line",
            "MCHE" : "MachineChest",
            "MREE" : "Mandreel",
            "NFLX" : "Nipcoflex",
            "PGUI" : "PalmGuide",
            "PARM" : "PrimaryArmSystem",
            "PTAN" : "PulpTank",
            "PUMP" : "Pump",
            "PURI" : "Purifier",
            "PROL" : "PushRoll",
            "REFN" : "Refiner",
            "RTAN" : "RejectTank",
            "ROSM" : "ReverseOsmosis",
            "RROL" : "RiderRoll",
            "SVAL" : "SafetyValve",
            "XSAW" : "Saw",
            "SWEI" : "ScaleWeight",
            "SPMP" : "ScrewPump",
            "SCRB" : "Scrubber",
            "SARM" : "SecondaryArmSystem",
            "SOPR" : "ShoePress",
            "SHOW" : "Shower",
            "SLIT" : "Slitter",
            "SPIN" : "Spinner",
            "SPEX" : "SpoolExtractor",
            "STRA" : "SteamTrap",
            "SUPR" : "SuctionPressRoll",
            "TREW" : "TableRewinder",
            "TOLI" : "TankiOli",
            "TCEL" : "TensionCell",
            "TREF" : "TicklingRefiner",
            "TSUC" : "TrimSuction",
            "UNWI" : "Unwinder",
            "VACU" : "Vacuum",
            "VSCR" : "VerticalScreen",
            "WLIN" : "WaterLine",
            "WSOF" : "WaterSoftener",
            "WWAT" : "WhiteWater",
            "WGRO" : "WireGuideRope",
            "WROL" : "WireRoll",
            "YANK" : "Yankee",
        } 
        return self.bagian
    
class equipment_code_dict():
    def divisi(self):
        self.divisi = { # type: ignore
            "AGIT" : "Agitator",
            "BELT" : "Belt",
            "BLAD" : "Blade",
            "CONT" : "Container",
            "CTRL" : "Control",
            "DEFL" : "Deflaker",
            "XFAN" : "Fan",
            "HAND" : "Handling",
            "HEEX" : "HeatExchanger",
            "LINE" : "Line",
            "PARM" : "PrimaryArm",
            "PUMP" : "Pump",
            "REFN" : "Refiner",
            "ROLL" : "Roll",
            "SCRN" : "Screen",
            "SARM" : "SecondaryArm",
            "SPRS" : "ShoePress",
            "SHOW" : "Shower",
            "VACM" : "Vacuum"
        }
        return self.divisi
    def subdivisi(self):
        self.subdivisi = { # type: ignore
            "DROL" : "DriveRoll",
            "SROL" : "StretcherRoll",
            "EROL" : "PressRoll",
            "IROL" : "IdleRoll",
            "UROL" : "PushRoll",
            "WTNK" : "WaterTank",
            "PTNK" : "PulpTank",
            "DTNK" : "DeconTank",
            "OTNK" : "OilTank",
            "CTNK" : "ChemicalTank",
            "PUMP" : "Pump",
            "FPMP" : "FanPump",
            "OPMP" : "OilPump",
            "IPMP" : "InjectionPump",
            "WLIN" : "WaterLine",
            "SLIN" : "SteamLine",
            "PLIN" : "PulpLine",
            "OLIN" : "OilLine",
            "ALIN" : "AirLine",
            "SENS" : "Sensor",
            "AGEN" : "Agent",
            "STRA" : "SolidTransport",
            "LTRA" : "LiquidTransport",
            "WATF" : "WaterFilter",
            "STOF" : "StockFilter",
            "OILF" : "OilFilter",
            "AIRF" : "AirFilter",
            "CENF" : "CentrifugalFan",
            "AXIF" : "AxialFan",
            "SCRP" : "Scraper",
            "SLIT" : "Slitter",
            "XSAW" : "Saw",
            "DOCT" : "Doctor",
            "HEAT" : "Heater",
            "COOL" : "Cooler",
            "AGIT" : "Agitator",
            "CLES" : "CleaningShower",
            "COAS" : "CoatingShower",
            "VACM" : "Vacuum",
            "REFN" : "Refiner",
            "DEFL" : "Deflaker",
            "SPRS" : "ShoePress",
            "SARM" : "SecondaryArm",
            "PARM" : "PrimaryArm",
            "TENB" : "TensionBelt",
        }
        return self.subdivisi